### ISSUE TITLE
kubernetes - io.k8s.api.autoscaling.v1.HorizontalPodAutoscalerStatus

### ISSUE THREAD

**Issue by Avi-Robusta** [Apollorion/manifests.io#92]
## Description of issue
on EKS v. 1.25
missing status conditions for hpa 
and currentMetrics field (this might be eks specific)

```
status:
  conditions:
  - lastTransitionTime: "2023-04-02T08:28:36Z"
    message: recent recommendations were higher than current one, applying the highest
      recent recommendation
    reason: ScaleDownStabilized
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2023-04-02T12:32:04Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2023-04-02T09:07:55Z"
    message: the desired replica count is more than the maximum replica count
    reason: TooManyReplicas
    status: "True"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 150
        averageValue: 301m
      name: cpu
    type: Resource
  currentReplicas: 2
  desiredReplicas: 2
  lastScaleTime: "2023-04-02T09:07:40Z"
  ```
